# Generated by Django 6.0.1 on 2026-02-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_education_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-folder', '-created_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='folder',
            field=models.CharField(choices=[('todo', 'Todo'), ('ideas', 'Ideas'), ('reminders', 'Reminders'), ('other', 'Other')], default='todo', max_length=50),
        ),
    ]
