# Generated by Django 6.0.1 on 2026-02-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=300),
        ),
    ]
