# Generated by Django 6.0.1 on 2026-02-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('text', models.CharField(max_length=220)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_todos', to='personal.profile')),
            ],
            options={
                'ordering': ['completed', '-created_at'],
            },
        ),
    ]
